// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/examples-gallery/CatalogPlates.tsx": () => import("../components/mockups/examples-gallery/CatalogPlates.tsx"),
  "./components/mockups/examples-gallery/Current.tsx": () => import("../components/mockups/examples-gallery/Current.tsx"),
  "./components/mockups/examples-gallery/IndexList.tsx": () => import("../components/mockups/examples-gallery/IndexList.tsx"),
  "./components/mockups/examples-gallery/SpecimenWall.tsx": () => import("../components/mockups/examples-gallery/SpecimenWall.tsx")
};
